# Generated by Django 5.1.7 on 2025-06-14 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='image',
            field=models.FileField(null=True, upload_to='property'),
        ),
    ]
