# Generated by Django 5.1.7 on 2025-06-26 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_propertytype_property_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='rentpayment',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_payment', to='core.unit'),
        ),
    ]
