# Generated by Django 5.1.7 on 2025-06-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rentpayment_created_at_alter_rentpayment_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentpayment',
            name='transaction_reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
